version: '3'
services:
    api-1:
        container_name: "api-1"
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - 5001:5000
        volumes:
            - /app/node_modules
            - ./server1:/app

    api-2:
        container_name: "api-2"
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - 5002:5000
        volumes:
            - /app/node_modules
            - ./server2:/app
            
    api-3:
        container_name: "api-3"
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - 5003:5000
        volumes:
            - /app/node_modules
            - ./server3:/app
                        

