version: '3'
services:
    api:
        container_name: "api"
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - /app/node_modules
            - ./server:/app
                        

