version: '3'
services:
    api:
        container_name: "api"
        build:
            dockerfile: Dockerfile
            context: ./server
        ports:
            - 80:5000
            - 5000:5000
        volumes:
            - /app/node_modules
            - ./server:/app
                        

