version: '3'
services:
    api:
        container_name: "api"
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - 5001:5000
        volumes:
            - /app/node_modules
            - ./server:/app
                        

